<a href="https://colab.research.google.com/github/sanket0708/AI_ML_Codes/blob/main/SupervisedAndUnsupervised/MultipleInputRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
import time

a = np.zeros(4)
print(a.shape)

b = np.random.randint(2)
print(b)

(4,)
1


In [22]:
c = np.arange(10)
print(c)

print(c[2])

print(c[-2])

try:
  c = a[10]
except Exception as e:
  print(e)

[0 1 2 3 4 5 6 7 8 9]
2
8
index 10 is out of bounds for axis 0 with size 4


In [31]:
a = np.arange(10)
print(a)

c = a[2:8:1]
print(c)

#three elements seperated by 2
d = a[2:7:2]
print(d)

#access all elements index 3 and above
e = a[3:]
print(e)

#below index 3
f = a[:3:]
print(f)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7]
[2 4 6]
[3 4 5 6 7 8 9]
[0 1 2]


In [36]:
a =np.array([1,2,3,4])
print(a)

#negate elements of a
b = -a
print(b)

#sum of all elements of a
sum = np.sum(a)
print(sum)

mean = np.mean(a)
print(mean)

d = a**2
print(d)

[1 2 3 4]
[-1 -2 -3 -4]
10
2.5
[ 1  4  9 16]


In [37]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a+b)

[ 6  8 10 12]


In [38]:
def my_dot(a,b):
  x = 0
  for i in range(a.shape[0]):
    x = x + a[i]*b[i]

  return x

In [39]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(my_dot(a,b))

70


In [40]:
#or we can write
print(np.dot(a,b))

70


In [44]:
a = np.zeros((1,5))
print(a.shape)

a = np.zeros((2,1))
print(a.shape)

(1, 5)
(2, 1)


In [48]:
a = np.arange(6).reshape(6, 1) #row,column
print(a)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [53]:
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements
print(a[0,2:7:1]) # 0th row ka index 2 se 6th tak print with step size 1

print(a[:,2:7:1])

a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[2 3 4 5 6]
[[ 2  3  4  5  6]
 [12 13 14 15 16]]


Lets start the gradient descent for multiple inputs


In [2]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

You will use the motivating example of housing price prediction. The training dataset contains three examples with four features (size, bedrooms, floors and, age) shown in the table below. Note that, unlike the earlier labs, size is in sqft rather than 1000 sqft.



In [4]:
X_train = np.array([[2104,5,1,45],[1416,3,2,40],[852,2,1,35]])
y_train = np.array([460,232,178])

In [10]:
print(X_train.shape)
print(X_train)
print(type(X_train))

print(y_train.shape)
print(y_train)
print(type(y_train))

(3, 4)
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
<class 'numpy.ndarray'>
(3,)
[460 232 178]
<class 'numpy.ndarray'>


In [11]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>


In [12]:
def predit_single_loop(x,w,b):
  n = x.shape[0]
  p = 0
  for i in range(n):
    p_i = x[i]*w[i]
    p = p + p_i
  p = p + b
  return p

In [18]:
x_vec = X_train[0,:]
print(x_vec)

#make a prediction
f_wb = predit_single_loop(x_vec,w_init,b_init)
print(f_wb)

[2104    5    1   45]
459.9999976194083


In [19]:
def predict(x,w,b):
  p = np.dot(x,w)+b
  return p

In [21]:
x_vec = X_train[1,:]
print(f"x_vec shape {x_vec.shape}, x_vec value: {x_vec}")

# make a prediction
f_wb = predict(x_vec,w_init, b_init)
print(f"f_wb shape {f_wb.shape}, prediction: {f_wb}")

x_vec shape (4,), x_vec value: [1416    3    2   40]
f_wb shape (), prediction: 231.9999983694081


In [22]:
def compute_cost(X,y,w,b):
  m = X.shape[0]
  cost = 0.0
  for i in range(m):
    f_wb_i = np.dot(X[i],w)+b
    cost += (f_wb_i - y[i])**2
  cost = cost / (2*m)
  return cost

In [23]:
# Compute and display cost using our pre-chosen optimal parameters.
cost = compute_cost(X_train, y_train, w_init, b_init)
print(f'Cost at optimal w : {cost}')

Cost at optimal w : 1.5578904428966628e-12


Compute Gradient with Multiple Variables

In [37]:
def compute_gradient(X,y,w,b):
  m,n = X.shape
  dj_dw = np.zeros((n,))
  dj_db = 0.

  for i in range(m):
    err = (np.dot(X[i],w)+b) - y[i]
    for j in range(n):
      dj_dw[j] = dj_dw[j] + err * X[i,j]
    dj_db = dj_db + err

  dj_dw /= m
  dj_db /= m
  return dj_db,dj_dw

In [38]:
#compute and display gradient
tmp_dj_dw, tmp_dj_db = compute_gradient(X_train, y_train, w_init, b_init)
print(f'dj_db at initial w,b: {tmp_dj_db}')
print(f'dj_dw at initial w,b: \n {tmp_dj_dw}')

dj_db at initial w,b: [-2.72623577e-03 -6.27197263e-06 -2.21745578e-06 -6.92403391e-05]
dj_dw at initial w,b: 
 -1.6739251501955248e-06


**Gradient Descent With Multiple Variables**

In [39]:
def gradient_descent(X,y,w_in,b_in,cost_function,gradient_function,alpha,num_iters):
  J_history = []
  w = copy.deepcopy(w_in)
  b = b_in

  for i in range(num_iters):
    dj_db,dj_dw = gradient_function(X,y,w,b)

    w = w - alpha * dj_dw
    b = b - alpha * dj_db

    if i < 100000:
      J_history.append(cost_function(X,y,w,b))



  return w,b,J_history

In [41]:
initial_w = np.zeros_like(w_init)
#print(initial_w)
initial_b = 0.

iterations = 1000
alpha = 5.0e-7

w_final,b_final,J_hist = gradient_descent(X_train,y_train,initial_w,initial_b,compute_cost,compute_gradient,alpha,iterations)

print(f"b,w found by gradient descent: {b_final:0.2f},{w_final} ")
m,_ = X_train.shape
for i in range(m):
    print(f"prediction: {np.dot(X_train[i], w_final) + b_final:0.2f}, target value: {y_train[i]}")

b,w found by gradient descent: -0.00,[ 0.20396569  0.00374919 -0.0112487  -0.0658614 ] 
prediction: 426.19, target value: 460
prediction: 286.17, target value: 232
prediction: 171.47, target value: 178
