<a href="https://colab.research.google.com/github/sanket0708/AI_ML_Codes/blob/main/PythonAndDS/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
def print_name(name):
  print("Hello my name is",name)

print_name("Sanket")

Hello my name is Sanket


In [6]:
for i in range(10):
  if (i+1)%2==0:
    print(i+1)


2
4
6
8
10


In [7]:
a = [1,2,3]
b = [4,5,6]

for i in range(len(a)):
  print(a[i] * b[i])

4
10
18


In [15]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([[1,2,3],[4,5,6]])

# d = [1,2,3]
# d = d*2
# print(d)

a = a*2  # 2 4 6
b = b+2 #6 7 8
print(a)
print(b)

np.sqrt(25)


[2 4 6]
[6 7 8]


np.float64(5.0)

In [21]:
print(a[0])
print(c[0][2])

2
3


In [30]:
d = np.array([1,2,3,4,5,6])
d = np.reshape(d,(2,3))
print(d)

print(np.sum(d,axis=0)) #axis = 0 means column , axis = 1 means row
print(np.sum(d,axis=1))

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


In [43]:
#MINI CHALLENGE

a = np.array([[30,70,95],[83,68,79],[91,39,45],[90,90,3],[80,81,82]])

mean_scores = np.mean(a,axis=1)

print(mean_scores)
print(np.where(mean_scores == max(mean_scores))[0][0])

subject_top_score = np.max(a,axis=0)
print(subject_top_score)

print(np.argmax(a,axis=0)) #returns the index of the maximum

[65.         76.66666667 58.33333333 61.         81.        ]
4
[91 90 95]
[2 3 0]
